//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\Administrator\Desktop\UG\FTS_SSS_1.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: YangShengyuan
//              Version: NX 10
//              Date: 11-15-2019  (Format: mm-dd-yyyy)
//              Time: 09:40
//
//==============================================================================

#ifndef FTS_SSS_1_H_INCLUDED
#define FTS_SSS_1_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf.h>
#include <uf_object_types.h>
#include <uf_ui.h>
#include <uf_modl.h>
#include <uf_obj.h>
#include <uf_part.h>
#include <uf_modl_types.h>
#include <uf_mtx.h>
#include <uf_defs.h>
#include <string>
#include <iostream>
#include <sstream>
#include <string>
#include <fstream>
#include <math.h>
#include <cmath>
#include <algorithm>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_FolderSelection.hxx>
//User defined
char msg[256] = "temptemp";
double start_radius;
double angle_space;
double tool_radius;
double feed_rate;
double cir_count;
double angle;
double angle_max;
tag_t DisplayBodyTag[1];
UF_MODL_ray_hit_point_info_p_t hit_list_p;
int num_desired = 1;
int num_results = 1;
double ray_direction[3] = {0,0,-1};
double point_origin[3] = {0.0,0.0,1000.0};
double pi = 3.141592653;
char File_dir[255];
char File_name[255];
char File_uncom_name[255];
char File_dir_un[255];
const double invariant_point [3] = {0,0,0};	
const double scale [3] = {1,1,1};
double zpt = 0;
double z_temp = 0;
double z_tool = 0;
double max;
double r_temp;
double i;
double rare_angle;



//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport FTS_SSS_1
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    FTS_SSS_1();
    ~FTS_SSS_1();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the FTS_SSS_1.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* start_radius0;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* angle_space0;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* tool_radius0;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* feed_rate0;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* rare_angle0;// Block type: Double
    NXOpen::BlockStyler::FolderSelection* FolderBrowser0;// Block type: NativeFolderBrowser
    
};
#endif //FTS_SSS_1_H_INCLUDED
